// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateQuartum(arg1) {
  return window['go']['main']['App']['CreateQuartum'](arg1);
}

export function GetAllQuarta() {
  return window['go']['main']['App']['GetAllQuarta']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
