// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDies(arg1:string):Promise<string>;

export function CreateQuartum(arg1:string):Promise<string>;

export function GetAllDies():Promise<string>;

export function GetAllQuarta():Promise<string>;

export function GetQuartaByDies(arg1:number):Promise<string>;

export function Greet(arg1:string):Promise<string>;
